import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const styles=readFileSync(new URL('../src/ui/styles.css',import.meta.url),'utf8');const shell=readFileSync(new URL('../src/ui/shell.css',import.meta.url),'utf8');const polish=readFileSync(new URL('../src/ui/mobile-polish.css',import.meta.url),'utf8');const refinements=readFileSync(new URL('../src/ui/mobile-flashcard-refinements.js',import.meta.url),'utf8');const index=readFileSync(new URL('../index.html',import.meta.url),'utf8');const app=readFileSync(new URL('../src/ui/app.js',import.meta.url),'utf8');const progressNav=readFileSync(new URL('../src/ui/progress-nav.js',import.meta.url),'utf8');const flashcards=readFileSync(new URL('../src/ui/flashcards-preview.js',import.meta.url),'utf8');const reporting=readFileSync(new URL('../src/ui/reporting.js',import.meta.url),'utf8');const flashcardStyles=readFileSync(new URL('../src/ui/flashcards-preview.css',import.meta.url),'utf8');
test('mobile shell keeps a shorter bottom navigation visible and clear of Learning controls',()=>{assert.match(styles,/html,body\{max-width:100%;overflow-x:hidden\}/);assert.match(styles,/\.app,\.topbar,#content,\.stack,\.home-grid,\.course-grid,\.evidence,\.session,.card\{min-width:0;max-width:100%\}/);assert.match(shell,/\.tabs\{position:fixed/);assert.match(shell,/body\.session-active \.app\{grid-template-rows:minmax\(0,1fr\);padding-bottom:calc\(64px \+ env\(safe-area-inset-bottom\)\)\}/);assert.match(shell,/body\.session-active \.tabs>\.tab\{height:44px;min-height:44px/);assert.doesNotMatch(shell,/body\.session-active \.tabs[^}]*display:none!important/);assert.match(flashcards,/document\.body\.classList\.remove\('session-active'\)/);});
test('icon navigation has four equal accessible touch targets',()=>{assert.match(shell,/\.tabs>\.tab\{height:54px;min-height:54px/);assert.match(shell,/\.tabs svg/);
 assert.doesNotMatch(flashcardStyles,/\.tabs \.tab\{flex:0 0 auto\}/);
});
test('main navigation uses distinct full-colour vector icons without changing its labels',()=>{
 const tabs=index.match(/<nav class="tabs"[^>]*>.*?<\/nav>/)[0];
 for(const name of ['course','flashcards','progress','settings'])assert.match(tabs,new RegExp(`nav-icon-${name}`));
 for(const colour of ['blue','coral','teal','violet'])assert.match(shell,new RegExp(`nav-${colour}-fill`));
 assert.match(shell,/\.tabs>\.nav-course\.active\{background:#e7f1ff\}/);
 assert.match(shell,/\.tabs>\.nav-flashcards\.active\{background:#fff0e8\}/);
 assert.match(shell,/\.tabs>\.nav-progress\.active\{background:#e5f7f1\}/);
 assert.match(shell,/\.tabs>\.nav-settings\.active\{background:#f1edff\}/);
 for(const label of ['Course','Flashcards','Progress','Settings'])assert.match(tabs,new RegExp(`aria-label="${label}"`));
});
test('the top menu shows four study destinations and keeps the rest inside Progress',()=>{
 const tabs=index.match(/<nav class="tabs"[^>]*>.*?<\/nav>/)[0];
 assert.match(tabs,/data-view="curriculum"[^>]*aria-label="Course"/);
 assert.match(tabs,/id="flashcards-preview-tab"/);
 assert.match(tabs,/id="progress-tab"/);
 assert.match(tabs,/data-view="settings"[^>]*aria-label="Settings"/);
 for(const label of ['Course','Flashcards','Progress','Settings'])assert.match(tabs,new RegExp(`<span class="sr-only">${label}</span>`));
 assert.match(index,/id="sync-status"/);
 assert.match(index,/id="sync-details"/);
 assert.match(index,/shell\.css\?v=5\.1\.\d+/);
 assert.match(index,/shell\.js\?v=5\.1\.\d+/);
 assert.doesNotMatch(tabs,/>Today</);
 assert.doesNotMatch(tabs,/id="report-tab"/);
 assert.doesNotMatch(tabs,/data-view="mistakes"/);
 assert.match(index,/id="daily-chrome"/);
 assert.match(index,/progress-triggers sr-only/);
 assert.match(index,/id="course-tab"/);
 assert.match(index,/id="evidence-tab"/);
 assert.match(index,/id="report-tab"/);
 assert.match(index,/data-view="mistakes"/);
 assert.match(index,/id="words-tab"/);
 assert.match(index,/progress-nav\.js\?v=5\.1\.\d+/);
 assert.match(app,/mistakes-view/);
 assert.doesNotMatch(progressNav,/id:'report'/);
 assert.match(progressNav,/id:'evidence'/);
 assert.match(progressNav,/openPane\('evidence'\)/);
 assert.match(progressNav,/classList.remove\('active'\)/);
 assert.match(flashcards,/open-flashcard-report/);
 assert.match(reporting,/back-to-flashcards/);
});
test('mobile flashcards use compact icon controls and robust speech wiring',()=>{assert.match(polish,/flashcard-listen::before/);assert.match(polish,/flashcard-tool-row button::before/);assert.match(refinements,/Listen to Dutch pronunciation/);assert.match(refinements,/speak\(text/);});
test('flashcard Listen speaks the Dutch word without the part-of-word label',()=>{assert.match(refinements,/cloneNode\(true\)/);assert.match(refinements,/querySelector\?\.\('\.flashcard-part'\)\?\.remove\(\)/);assert.match(refinements,/spoken\.textContent/);});
test('mobile header keeps version, daily completion and sync status on one row',()=>{assert.match(shell,/\.topbar\{display:grid!important;grid-template-columns:minmax\(0,1fr\) auto auto/);assert.match(shell,/\.daily-chrome\{grid-column:2;grid-row:1/);assert.match(shell,/\.sync-status\{grid-column:3;grid-row:1/);assert.match(shell,/body\.session-active \.brand p\{display:block!important\}/);assert.match(index,/id="sync-status"/);});
test('active sessions combine Zin, progress, pause and sync while retaining bottom navigation',()=>{const sessionStyles=readFileSync(new URL('../src/ui/v51.css',import.meta.url),'utf8');assert.match(shell,/body\.session-active \.topbar\{display:contents!important\}/);assert.match(shell,/body\.session-active \.topbar>\.brand\{display:none!important\}/);assert.match(shell,/body\.session-active \.topbar>#sync-status\{display:none!important\}/);assert.match(sessionStyles,/\.session-head\{display:grid;grid-template-columns:auto minmax\(0,1fr\) auto/);assert.match(sessionStyles,/\.session-controls \.sync-status,\.session-controls \.session-pause\{width:44px;height:44px/);assert.match(app,/className='session-controls'/);assert.match(app,/className='sync-status session-sync'/);assert.match(app,/proxy\.addEventListener\('click',\(\)=>syncTrigger\.click\(\)\)/);assert.match(app,/if\(sessionSync\)sessionSync\.disabled=false/);});
test('Flashcard start opens the protected daily queue without a confirmation',()=>{const start=flashcards.split('function startSession(){')[1]?.split('function current(){')[0];assert.ok(start);assert.match(start,/if\(c\.complete\|\|\(!c\.dueReview&&!c\.dueNew\)\)return/);assert.match(start,/newLimit:c\.dueNew/);assert.match(start,/renderCard\(\)/);assert.doesNotMatch(start,/confirm\(/);assert.doesNotMatch(index,/flashcard-start-warning\.js/);});
test('mobile polish remains shipped in the current build',()=>{assert.match(index,/V5\.1\.\d+/);assert.match(index,/mobile-polish\.css\?v=5\.1\.\d+/);assert.match(index,/mobile-flashcard-refinements\.js\?v=5\.1\.\d+/);});
test('Listen starts in the same tap so iPhone can play audio',()=>{assert.doesNotMatch(app,/Promise\.resolve\(\)\.then\(fn\)/);assert.match(app,/const result=fn\(\)/);assert.match(app,/listen-example.*speak\(/);assert.match(app,/is-development/);});
