import {registerPacks} from '../content/registry.js';
import {freshState,ensureDay,activeConcept,unlocked,phase,teachConcept,prepareQuestion,markWordsTaught,startProof,proofEligibility,submit,useHelp,statistics} from '../engine/learner.js';
import {createRepository,STORAGE_KEY} from '../engine/persistence.js';
import {dayKey,addDays,pct} from '../engine/util.js';
import {labels} from '../engine/scoring.js';
import {chooseTile,removeTile,bankAnswer,correctiveFeedback} from '../engine/exercises.js';
import {bindPeek} from './peek.js';
import {dutchVoice,speak} from './speech.js';
const el=document.querySelector('#content'),message=document.querySelector('#system-message');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let content,state,repo,view='today',dev=false,selectedConcept=null,lastFeedback=null;
let disposePeek=()=>{};
const now=()=>dev&&state?.settings?.debugDate?new Date(state.settings.debugDate+'T12:00:00'):new Date();
const statusLabels={'learning':'Learning','proof-ready':'Proof Ready','retention-wait':'Retention pending','retention-ready':'Retention Ready','mastered':'Mastered','reinforcement':'Reinforcement'};
const status=id=>statusLabels[phase(state.progress[id],dayKey(now()))];
function notify(t){message.innerHTML=t?`<div class="error-message">${esc(t)}</div>`:'';}
function button(id,label,primary=true,disabled=false){return `<button id="${id}" class="${primary?'primary':'secondary'}" ${disabled?'disabled':''}>${esc(label)}</button>`;}
function on(id,fn){document.getElementById(id)?.addEventListener('click',()=>Promise.resolve().then(fn).catch(e=>notify(e.message)));}
async function transaction(fn){
 const run=async()=>{const next=repo.load();const result=fn(next);repo.save(next);state=next;return result};
 // Web Locks serialise writes from tabs on this origin. Fallback stays functional in older browsers.
 if(navigator.locks)return navigator.locks.request(dev?STORAGE_KEY+'-sandbox':STORAGE_KEY,run);
 return run();
}
function metrics(list){const s=statistics(list);return `<div class="metrics"><div class="metric"><span class="eyebrow">Grammar</span><span class="n">${pct(s.grammar,s.total)}</span></div><div class="metric"><span class="eyebrow">Spelling</span><span class="n">${pct(s.spelling,s.spellingTotal)}</span></div><div class="metric"><span class="eyebrow">Independent</span><span class="n">${s.independent}</span></div><div class="metric"><span class="eyebrow">Word recall</span><span class="n">${pct(s.recall,s.total)}</span></div></div>`}
function proofReport(){const r=state.lastProof;if(!r)return '';return `<article class="card evidence-card proof-report"><div class="eyebrow">Latest ${esc(r.type)} result · ${esc(r.concept)}</div><h2>${r.passed?'Grammar proven in both directions':'More practice before the next test'}</h2><p>NL → EN: ${r.directions['nl-en'].correct}/${r.directions['nl-en'].total} · EN → NL: ${r.directions['en-nl'].correct}/${r.directions['en-nl'].total}</p><p class="muted small">${r.passed?(r.type==='mastery'?'Retention opens '+esc(state.progress[r.concept].retentionDue)+'.':'The next concept is unlocked. This one will return for maintenance.'):'Complete eight successful practice questions before trying fresh proof material again.'}</p></article>`}
function sessionChrome(active){document.body.classList.toggle('session-active',active);const footer=document.querySelector('footer');if(active)footer.setAttribute('aria-hidden','true');else footer.removeAttribute('aria-hidden');}
function render(){
 disposePeek();sessionChrome(false);
 notify('');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
 if(view==='today')renderToday();else if(view==='curriculum')renderCourse();else if(view==='mistakes')renderMistakes();else if(view==='settings')renderSettings();
 if(dev)el.insertAdjacentHTML('afterbegin',`<div class="debug-banner">Developer sandbox · ${dayKey(now())} · Real learning progress is separate.</div>`);
}
async function show(v){view=v;selectedConcept=null;lastFeedback=null;await transaction(s=>ensureDay(s,now()));render();}
function renderToday(){
 const id=activeConcept(state,content),c=content.conceptById[id],p=state.progress[id],date=dayKey(now()),done=state.daily.count>=20;
 el.innerHTML=`<section class="stack"><div class="home-grid"><article class="card summary"><div class="eyebrow">Today's practice</div><div class="big">${state.daily.count} <span class="muted">/ 20</span></div><p class="muted">${done?'Today’s work is complete. Mistakes shape future practice.':'A finite daily session. Teaching is extra; scored questions stop at 20.'}</p><div class="progress-track" role="progressbar" aria-label="Daily questions" aria-valuenow="${state.daily.count}" aria-valuemin="0" aria-valuemax="20"><div class="progress-fill" style="width:${state.daily.count*5}%"></div></div>${button('start',state.proof?'Resume '+state.proof.type+' test':state.daily.count?'Continue today’s practice':'Start today’s practice',true,done)}</article><article class="card concept"><div class="row"><span class="eyebrow">${esc(c.level)} · ${esc(id)}</span><span class="status">${status(id)}</span></div><h2>${esc(c.title)}</h2><p class="muted">${p.practiceAttempts} practice attempts · ${p.independent} independent answers</p><div class="phase-steps">Teach → Recognise → Construct → Produce → Repeat → <strong>Prove</strong></div>${proofAction(id)}${button('lesson','Read the lesson',false)}${metrics(state.attempts.filter(x=>x.concept===id))}</article></div>${proofReport()}${done?`<article class="card evidence-card"><h2>Today’s evidence</h2>${metrics(state.attempts.filter(x=>x.date===date))}<p class="muted">You can read lessons and review mistakes at any time.</p></article>`:''}</section>`;
 on('start',()=>openQuestion());on('lesson',()=>renderLesson(id,false));bindProof(id);
}
function proofAction(id){const p=state.progress[id],ph=phase(p,dayKey(now()));
 if(ph==='proof-ready'||ph==='retention-ready'){
 const type=ph==='proof-ready'?'mastery':'retention',reason=proofEligibility(state,content,id,type,now());
 return `<div class="rule"><strong>${type==='mastery'?'Ready for mastery proof':'Ready to check retention'}</strong><p class="small">${type==='mastery'?'10 unseen Dutch → English and 10 unseen typed English → Dutch.':'5 unseen Dutch → English and 5 unseen typed English → Dutch.'} 100% grammar in each direction. No word help.</p>${button('proof',type==='mastery'?'Start Mastery Test':'Start Retention Test',true,!!reason)}${reason?`<p class="small muted">${esc(reason)}</p>`:''}</div>`;
 }
 if(ph==='retention-wait')return `<div class="rule"><strong>Retention test opens ${esc(p.retentionDue)}</strong><p class="small">Three days after mastery. Until then, practise and revisit vocabulary within your daily 20.</p></div>`;
 return `<p class="muted small">${p.masteredAt?'Retained and in maintenance.':`Proof opens after 40 practice attempts. Independent production is tracked separately.${p.remedial?' '+p.remedial+' successful remedial questions remain.':''}`}</p>`;
}
function bindProof(id){on('proof',()=>proofPreparation(id));}
function vocabularyFor(id){return [...new Map(content.sentences.filter(x=>x.concept===id).flatMap(x=>x.vocabulary).map(w=>[w.id,w])).values()]}
function vocabularyHTML(words){return `<div class="vocabulary-list">${words.map(w=>`<div class="row"><strong lang="nl">${esc(w.nl)}</strong><span>${esc(w.en)}${w.mature?' <span class="pill">Mature card</span>':''}</span></div>`).join('')}</div>`}
function renderLesson(id,continueSession){
 sessionChrome(true);
 const c=content.conceptById[id];if(!unlocked(c,state))return;
 el.innerHTML=`<section class="session stack"><article class="card question-card"><span class="direction">Teach · not scored</span><h2>${esc(id)} · ${esc(c.title)}</h2><p>${esc(c.rule)}</p><div class="teach-panel"><div class="prompt" lang="nl">${esc(c.example)}</div><p>${esc(c.translation)}</p>${button('listen-example','Listen to the example',false)}</div><details><summary>Vocabulary for this concept</summary>${vocabularyHTML(vocabularyFor(id))}</details><div class="actions">${button('learned',continueSession?'Got it — let’s practise':'Back to today')}</div></article></section>`;
 transaction(s=>teachConcept(s,id,content)).catch(e=>notify(e.message));on('listen-example',()=>speak(c.example,notify));on('learned',()=>continueSession?openQuestion():show('today'));
}
async function proofPreparation(id){
 const type=phase(state.progress[id],dayKey(now()))==='proof-ready'?'mastery':'retention';
 const words=vocabularyFor(id).filter(w=>!state.words[w.id]?.taughtAt);
 if(words.length){
  el.innerHTML=`<section class="session"><article class="card evidence-card"><span class="direction">Vocabulary reminder · not scored</span><h2>Before your ${type} test</h2><p>Here is the remaining vocabulary for this concept. The test uses unseen sentences, with no assistance once it starts.</p>${vocabularyHTML(words)}${button('begin-proof','Ready — start the test')}<div class="spaced">${button('cancel-proof','Back to today',false)}</div></article></section>`;
  on('begin-proof',async()=>{await transaction(s=>{for(const w of words)markWordsTaught(s,{vocabulary:[w]},dayKey(now()));startProof(s,content,id,type,now())});await openQuestion()});on('cancel-proof',()=>show('today'));
 }else{await transaction(s=>startProof(s,content,id,type,now()));await openQuestion();}
}
async function openQuestion(){
 lastFeedback=null;const q=await transaction(s=>prepareQuestion(s,content,now(),s.settings.listening&&!!dutchVoice()));
 if(!q){view='today';render();return;}if(q.teachingConcept){renderLesson(q.teachingConcept,true);return;}
 const item=content.byId[q.sourceId];const unknown=item.vocabulary.filter(w=>!state.words[w.id]?.taughtAt||(state.words[w.id].weakness>=3&&state.words[w.id].taughtAt<dayKey(now())));
 if(['practice','maintenance'].includes(q.phase)&&unknown.length){
  el.innerHTML=`<section class="session"><article class="card question-card"><span class="direction">Vocabulary reminder · not scored</span><h2>A few words before you practise</h2>${vocabularyHTML(unknown)}<p class="muted">You still have ${20-state.daily.count} scored questions today.</p><div class="actions">${button('words-learned','Got it — practise')}</div></article></section>`;
  on('words-learned',async()=>{await transaction(s=>markWordsTaught(s,item,dayKey(now())));renderQuestion(q)});return;
 }
 renderQuestion(q);
}
function renderQuestion(q){
 disposePeek();sessionChrome(true);
 const item=content.byId[q.sourceId];let selection=[],raw='',locked=false;
 const titles={choice:'Choose the English meaning',wordbank:'Build the Dutch sentence',typed:'Write the Dutch sentence',gap:'Fill the missing form',form:'Choose the correct form','correct-sentence':'Choose the matching Dutch sentence',correction:'Correct the Dutch sentence',listening:'Listen and choose the meaning'};
 el.innerHTML=`<section class="session"><div class="session-head"><strong>Question ${state.daily.count+1} of 20 today</strong><span class="pill">${esc(q.concept)} · ${esc(q.phase)}</span></div>${state.proof?`<p class="muted small">Test: ${state.proof.index+1} / ${state.proof.questions.length}. Each direction must reach 100% grammar.</p>`:''}<article class="card question-card"><span class="direction">${q.direction==='en-nl'?'English → Dutch':'Dutch → English'}</span><div class="q-type">${titles[q.kind]}</div><h2 class="prompt" ${q.direction==='nl-en'&&q.kind!=='listening'||['gap','form','correction'].includes(q.kind)?'lang="nl"':''}>${esc(q.prompt)}</h2>${q.cue?`<p class="muted">Meaning: ${esc(q.cue)}</p>`:''}${q.kind==='listening'?`${button('play','Play Dutch audio',false)}<button id="text-fallback" class="text-link">Audio unavailable? Use text</button>`:''}<div id="answer-area"></div><div id="help-area"></div><div id="feedback" aria-live="polite"></div><div class="actions">${button('check','Check answer')}</div></article><button id="pause" class="text-link">Pause — progress is saved</button></section>`;
 const area=document.getElementById('answer-area');
 if(q.options){area.innerHTML=`<div class="answers">${q.options.map((o,i)=>`<button class="choice" data-choice="${i}" aria-pressed="false">${esc(o)}</button>`).join('')}</div>`;area.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{raw=q.options[Number(b.dataset.choice)];area.querySelectorAll('button').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))})});}
 else if(q.kind==='wordbank'){
  area.innerHTML='<div id="built" class="built" aria-label="Your sentence"></div><div id="bank" class="wordbank" aria-label="Available words"></div><p class="muted small">Tap a chosen word to put it back. Extra words are deliberate.</p>';
  const draw=()=>{document.getElementById('built').innerHTML=selection.map(id=>`<button class="word" data-remove="${id}" aria-label="Remove ${esc(q.bank.find(x=>x.id===id).text)}">${esc(q.bank.find(x=>x.id===id).text)}</button>`).join('');document.getElementById('bank').innerHTML=q.bank.map(t=>`<button class="word ${selection.includes(t.id)?'used':''}" data-tile="${t.id}" ${selection.includes(t.id)?'disabled':''}>${esc(t.text)}</button>`).join('');area.querySelectorAll('[data-tile]').forEach(b=>b.onclick=()=>{selection=chooseTile(selection,b.dataset.tile,q.bank);draw()});area.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{selection=removeTile(selection,b.dataset.remove);draw()});raw=bankAnswer(selection,q.bank)};draw();
 }else{area.innerHTML='<label for="typed-answer" class="sr-only">Your Dutch answer</label><input id="typed-answer" class="input" lang="nl" placeholder="Type in Dutch" autocomplete="off" autocorrect="off" autocapitalize="sentences" spellcheck="false">';const input=document.getElementById('typed-answer');input.oninput=()=>raw=input.value;input.onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing)check()};}
 if(q.direction==='en-nl'&&['typed','wordbank'].includes(q.kind)&&['practice','maintenance'].includes(q.phase)){
  const help=document.getElementById('help-area');help.innerHTML=`<div class="assist-row">${button('help','Hold for word',false)}<span id="hint" class="hint" aria-live="polite"></span></div>`;
  disposePeek=bindPeek(document.getElementById('help'),document.getElementById('hint'),{
   reveal:item.vocabulary.map(w=>w.nl+' — '+w.en).join(' · '),
   onUse:()=>transaction(s=>{if(s.pending?.id!==q.id)throw Error('This question has changed.');useHelp(s)}),
   onError:e=>notify(e.message)
  });
 }
 async function check(){if(locked)return;if(!raw.trim()){notify('Enter or choose an answer first.');return;}locked=true;disposePeek();
  try{const rec=await transaction(s=>submit(s,content,q.id,raw,now()));lastFeedback=rec;const feedback=correctiveFeedback(q,item,raw,rec);
   el.querySelectorAll('input,button').forEach(b=>b.disabled=true);document.getElementById('feedback').innerHTML=`<div class="feedback ${rec.grammar===true?(rec.spelling===false?'warn':'ok'):'bad'}"><strong>${rec.grammar===true?(rec.spelling===false?'Grammar correct · spelling to revisit':'Grammar correct'):rec.grammar===null?'Vocabulary needs review':'Let’s revisit this pattern'}</strong><span class="correct" lang="nl">${feedback.words.map(part=>part.changed?`<mark class="problem-char">${esc(part.text)}</mark>`:esc(part.text)).join(' ')}${esc(feedback.punctuation)}</span><span class="meaning">${esc(feedback.meaning)}</span>${feedback.differences.length?`<p lang="nl">${feedback.differences.map(esc).join(' · ')}</p>`:''}${feedback.explanation?`<p>${esc(feedback.explanation)}</p>`:''}${rec.capitalization===false?'<p>Start the sentence with a capital letter. This is separate from grammar.</p>':''}<div class="badges"><span class="badge">Grammar ${rec.grammar===true?'✓':rec.grammar===null?'unproven':'review'}</span>${rec.spelling!==null?`<span class="badge">Spelling ${rec.spelling?'✓':'review'}</span>`:''}${rec.capitalization!==null?`<span class="badge">Capitalisation ${rec.capitalization?'✓':'review'}</span>`:''}${rec.assisted?'<span class="badge">Word help used</span>':''}</div></div>`;
   document.querySelector('.actions').innerHTML=button('next',state.daily.count===20?'Finish today':!state.proof&&['mastery','retention'].includes(q.phase)?'View test result':'Continue');
   on('next',()=>state.daily.count===20||!state.proof&&['mastery','retention'].includes(q.phase)?show('today'):openQuestion());document.getElementById('next').focus();
  }catch(e){locked=false;notify(e.message)}
 }
 on('check',check);on('pause',()=>show('today'));on('play',()=>speak(item.nl,notify));on('text-fallback',async()=>{await transaction(s=>{if(s.pending?.id===q.id){s.pending.kind='choice';s.pending.prompt=item.nl}});renderQuestion(state.pending)});
}
function renderCourse(){
 if(selectedConcept){const c=content.conceptById[selectedConcept],p=state.progress[c.id];el.innerHTML=`<section class="stack"><article class="card evidence-card"><div class="row"><h2>${esc(c.id)} · ${esc(c.title)}</h2><span class="status">${status(c.id)}</span></div>${metrics(state.attempts.filter(x=>x.concept===c.id))}<p>${p.practiceAttempts}/40 practice attempts · ${p.independent} independent answers</p>${proofAction(c.id)}${button('read-course','Read lesson',false)}<div class="spaced">${button('back-course','Back to course',false)}</div></article></section>`;on('read-course',()=>renderLesson(c.id,false));on('back-course',()=>{selectedConcept=null;renderCourse()});bindProof(c.id);return;}
 el.innerHTML=`<section class="stack"><article class="card evidence-card"><h2>Your course</h2><p class="muted">${content.concepts.filter(c=>state.progress[c.id].masteredAt).length} of ${content.concepts.length} concepts retained. A new concept opens after the previous retention test.</p></article><div class="course-grid">${[...new Set(content.concepts.map(c=>c.level))].map(level=>`<div class="course-group"><div class="eyebrow">${level}</div>${content.concepts.filter(c=>c.level===level).map(c=>`<button class="course-item" data-concept="${c.id}" ${unlocked(c,state)?'':'disabled'}><div class="row"><span class="eyebrow">${c.id}</span><span class="status">${unlocked(c,state)?status(c.id):'Locked'}</span></div><h3>${esc(c.title)}</h3><div class="muted small">${unlocked(c,state)?state.progress[c.id].practiceAttempts+' practice attempts':'After '+c.prerequisites.join(', ')+' retention'}</div></button>`).join('')}</div>`).join('')}</div><article class="card evidence-card"><h3>Room to grow: A2 → B1</h3><p class="muted">Future content packs can extend this course. These levels are not included in V5.</p></article></section>`;
 el.querySelectorAll('[data-concept]').forEach(b=>b.onclick=()=>{selectedConcept=b.dataset.concept;renderCourse()});
}
function renderMistakes(){
 const bad=state.attempts.filter(x=>x.grammar!==true||x.spelling===false||x.capitalization===false||x.assisted);const counts={};for(const a of bad){const type=a.errorType||(a.capitalization===false?'capitalization':'translation');counts[type]=(counts[type]||0)+1;}
 const weak=Object.entries(state.words).filter(([,w])=>w.weakness>0).sort((a,b)=>b[1].weakness-a[1].weakness).slice(0,10);const vocab=new Map(content.sentences.flatMap(x=>x.vocabulary).map(w=>[w.id,w]));
 el.innerHTML=`<section class="stack"><article class="card evidence-card"><h2>Mistakes & weak areas</h2><p class="muted">Useful evidence, not penalties. Successful recall gradually reduces repetition priority.</p>${bad.length?`<div class="error-grid">${Object.entries(counts).map(([k,n])=>`<div class="error-chip"><span class="eyebrow">${esc(labels[k]||k)}</span><span class="n">${n}</span><span class="small muted">recorded so far</span></div>`).join('')}</div>`:'<div class="empty">No mistakes recorded yet. Start today’s practice to build your learning evidence.</div>'}</article>${weak.length?`<article class="card evidence-card"><h3>Current word priorities</h3><p>${weak.map(([id])=>esc(vocab.get(id)?.nl||id)).join(' · ')}</p></article>`:''}<div class="recent-mistakes">${bad.slice(-25).reverse().map(a=>`<article class="card evidence-card"><div class="eyebrow">${esc(a.concept)} · ${esc(labels[a.errorType]||(a.capitalization===false?'Capitalisation':'Review'))}</div><h3>${esc(a.prompt)}</h3><p class="small">Your answer: ${esc(a.answer)}<br>Model: <strong>${esc(a.correctSentence||content.byId[a.sourceId]?.nl||a.expected)}</strong><br>${esc(a.englishMeaning||content.byId[a.sourceId]?.en||'')}</p>${a.tip?`<p class="tipbox">${esc(a.tip)}</p>`:''}</article>`).join('')}</div></section>`;
}
function renderSettings(){
 el.innerHTML=`<section class="stack"><article class="card evidence-card"><h2>Your app</h2><div class="settings-row row"><label for="listening">Include Dutch listening when a voice is available</label><input id="listening" type="checkbox" ${state.settings.listening?'checked':''}></div><p class="muted small">${dutchVoice()?'Dutch voice available.':'No Dutch voice detected yet. Other exercise types remain available.'} Offline audio depends on an installed device voice.</p><h3>Install & use offline</h3><p>On iPhone or iPad, open the hosted app in Safari, tap Share, then Add to Home Screen. On supported Mac Safari versions, use Add to Dock. Open online once and wait for “Ready offline” below.</p><h3>Progress stays on this device</h3><p class="muted">Export a backup before changing devices, clearing browser data, or moving to a different hosted address. V5 does not sync automatically.</p>${button('export','Export progress',false)} <label class="text-link" for="import">Import V5 backup</label><input id="import" type="file" accept="application/json,.json" class="input spaced"><p class="small muted">Import replaces this app’s current progress. Keep your export first.</p>${state.migration?`<p class="notice">${esc(state.migration.from)} progress imported on this browser origin.</p>`:''}</article><article class="card evidence-card"><details ${dev?'open':''}><summary>Developer & test controls</summary><p class="muted">Use a separate sandbox to jump through states without changing real learning history.</p>${button('toggle-dev',dev?'Return to real learning':'Open developer sandbox',false)}${dev?`<div class="stack spaced"><label>Concept <select id="dev-concept">${content.concepts.map(c=>`<option value="${c.id}">${c.id} · ${esc(c.title)}</option>`).join('')}</select></label><label>State <select id="dev-state"><option value="learning">Learning</option><option value="construct">Construct</option><option value="produce">Produce / Repeat</option><option value="proof-ready">Proof Ready</option><option value="retention-wait">Retention pending</option><option value="retention-ready">Retention Ready</option><option value="mastered">Mastered</option><option value="reinforcement">Reinforcement</option></select></label>${button('jump','Apply sandbox state',false)}${button('next-day','Advance sandbox by one day',false)}${button('reset-sandbox','Fresh sandbox',false)}</div>`:''}</details></article></section>`;
 document.getElementById('listening').onchange=async e=>{try{await transaction(s=>s.settings.listening=e.target.checked)}catch(err){notify(err.message)}};
 on('export',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([repo.export(state)],{type:'application/json'}));a.download=`dutch-trainer-v5${dev?'-sandbox':''}-${dayKey(now())}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
 document.getElementById('import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(!confirm('Replace current V5 progress with this backup?'))return;const text=await f.text();state=repo.import(text);render();}catch(err){notify(err.message)}};
 on('toggle-dev',()=>{dev=!dev;repo=createRepository(localStorage,content,{key:dev?STORAGE_KEY+'-sandbox':STORAGE_KEY});state=repo.load();repo.save(state);render()});
 on('next-day',async()=>{await transaction(s=>{s.settings.debugDate=addDays(dayKey(now()),1);ensureDay(s,new Date(s.settings.debugDate+'T12:00:00'))});render()});
 on('reset-sandbox',()=>{state=freshState(content);repo.save(state);render()});
 on('jump',async()=>{const id=document.getElementById('dev-concept').value,ph=document.getElementById('dev-state').value;await transaction(s=>{const idx=content.concepts.findIndex(c=>c.id===id);for(const [i,c]of content.concepts.entries()){s.progress[c.id]=freshState(content).progress[c.id];if(i<idx)Object.assign(s.progress[c.id],{status:'mastered',masteredAt:dayKey(now()),nextMaintenance:addDays(dayKey(now()),7),taught:true});}const p=s.progress[id];Object.assign(p,{taught:ph!=='learning',recognised:ph==='learning'?0:4,constructed:['learning','construct'].includes(ph)?0:4,practiceAttempts:['learning','construct','produce'].includes(ph)?0:40,independent:['learning','construct','produce'].includes(ph)?0:8,status:['construct','produce'].includes(ph)?'learning':ph});if(ph.startsWith('retention'))p.retentionDue=addDays(dayKey(now()),ph==='retention-ready'?0:3);if(['mastered','reinforcement'].includes(ph)){p.masteredAt=dayKey(now());p.nextMaintenance=dayKey(now())}s.daily={date:dayKey(now()),count:0};s.pending=null;s.proof=null;s.lastProof=null;s.retries=[];});view='today';render()});
}
async function init(){
 const manifestURL=new URL('../content/packs.json',import.meta.url);const response=await fetch(manifestURL);if(!response.ok)throw Error('The course could not load. Reconnect and refresh once.');const manifest=await response.json();const packs=await Promise.all(manifest.packs.map(async path=>{const r=await fetch(new URL(path,manifestURL));if(!r.ok)throw Error('A course pack could not load. Reconnect and refresh.');return r.json()}));content=registerPacks(packs);repo=createRepository(localStorage,content);state=repo.load();repo.save(state);await transaction(s=>ensureDay(s));render();
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view).catch(e=>notify(e.message)));
 window.addEventListener('storage',e=>{if(e.key===(dev?STORAGE_KEY+'-sandbox':STORAGE_KEY)){state=repo.load();view='today';render();notify('Progress updated in another tab. Continue from the saved question.')}});
 if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('./sw.js',{scope:'./'});await navigator.serviceWorker.ready;document.getElementById('offline-status').textContent='Ready offline · progress saved locally';}catch{document.getElementById('offline-status').textContent='Offline cache unavailable — keep this page online';}}
 else document.getElementById('offline-status').textContent='Offline installation needs HTTPS hosting';
}
init().catch(e=>{el.innerHTML='<article class="card evidence-card"><h2>The app could not open safely</h2><p>Your stored progress has not been cleared. Export or preserve the existing browser data before recovery.</p><p>Refresh after reconnecting if the course could not load.</p></article>';notify(e.message)});
