import {STORAGE_KEY} from '../engine/persistence.js';
import {PRODUCTION_DAILY_LIMIT,productionAttemptsToday,recordProductionAttempt,PRODUCTION_STAGE} from '../engine/flashcards.js';
import {CONTEXTUAL_DAILY_LIMIT,contextualAttemptsToday,contextualRecallCandidates,contextualExercise} from '../engine/contextual-recall.js';
import {chooseSentence} from '../engine/sentence-bank.js';
import {cachedSentenceBank} from './sentence-bank-client.js';

const content=document.getElementById('content');
const tab=document.getElementById('flashcards-preview-tab');
let cardsCache=null,scheduled=false,busy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=s=>String(s??'').trim().toLocaleLowerCase('nl-NL').replace(/[.!?]+$/,'').replace(/\s+/g,' ');
const dayKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function state(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')||{};}catch{return{};}}
function saveState(s){localStorage.setItem(STORAGE_KEY,JSON.stringify(s));}
async function cards(){if(cardsCache)return cardsCache;const c=await import('https://dabutchart-sudo.github.io/flashcards/constants.js'),rows=[],size=1000;for(let from=0;;from+=size){const res=await fetch(`${c.SUPABASE_URL}/rest/v1/cards?select=*`,{headers:{apikey:c.SUPABASE_ANON_KEY,Authorization:`Bearer ${c.SUPABASE_ANON_KEY}`,Range:`${from}-${from+size-1}`,'Range-Unit':'items'}});if(!res.ok)throw new Error(`Could not read cards (${res.status}).`);const page=await res.json();rows.push(...page);if(page.length<size)break;}cardsCache=rows;return rows;}

async function status(){const s=state(),today=dayKey(),overallLeft=Math.max(0,PRODUCTION_DAILY_LIMIT-productionAttemptsToday(s,today)),done=contextualAttemptsToday(s,today);try{const all=await cards(),candidates=contextualRecallCandidates(all,s,{today});return{candidate:candidates[0]||null,done,overallLeft};}catch{return{candidate:null,done,overallLeft};}}

async function inject(){const anchor=document.getElementById('independent-recall-pilot')||document.querySelector('.production-practice-callout');if(!anchor||document.getElementById('contextual-recall-pilot'))return;const info=await status();if(!info.candidate&&!info.done)return;const host=document.createElement('div');host.id='contextual-recall-pilot';host.className='independent-recall-pilot';host.innerHTML=`<div><strong>Contextual sentence pilot</strong><div class="mini">${info.done?'Contextual practice complete for today.':'Use a mature word inside a full Dutch sentence. Developing words are prioritised; proven words rest until a later maintenance check is due.'}</div></div><button class="secondary" ${!info.candidate||!info.overallLeft?'disabled':''}>${info.candidate&&info.overallLeft?'Build 1 sentence':'Done for today'}</button>`;anchor.insertAdjacentElement('afterend',host);host.querySelector('button')?.addEventListener('click',start);}

function usedContexts(s,cardId){const values=[];for(const a of s.flashcardProduction?.attempts||[]){if(a?.meaningful===true&&a.stage===PRODUCTION_STAGE.CONTEXTUAL&&String(a.cardId)===String(cardId)&&a.expected)values.push(a.expected);}for(const a of s.attempts||[]){if(Array.isArray(a?.words)&&a.words.includes(`card:${cardId}`)&&a.direction==='en-nl'&&a.independent===true&&a.grammar===true&&a.spelling!==false&&a.assisted!==true&&a.correctSentence)values.push(a.correctSentence);}return new Set(values.map(clean).filter(Boolean));}
async function rotatingSentence(record,s){try{const bank=await cachedSentenceBank(record),used=usedContexts(s,record.id),fresh=bank.filter(pair=>!used.has(clean(pair.nl)));return chooseSentence(fresh.length?fresh:bank);}catch{return null;}}

async function start(){if(busy)return;busy=true;try{const s=state(),today=dayKey(),all=await cards(),record=contextualRecallCandidates(all,s,{today})[0];if(!record){tab?.click();return;}const pair=await rotatingSentence(record,s);renderQuestion(s,today,record,contextualExercise(record,Math.random,pair));}catch(e){alert(e.message);}finally{busy=false;}}

function renderQuestion(s,today,record,exercise){let selected=[];const render=()=>{const answer=selected.map(i=>exercise.tiles[i]).join(' '),remaining=exercise.tiles.map((tile,i)=>({tile,i})).filter(x=>!selected.includes(x.i));content.innerHTML=`<section class="flashcard-session"><div class="session-head"><strong>Contextual practice</strong><span class="pill">Sentence</span></div><article class="card production-card"><div class="eyebrow">English → Dutch · use <span lang="nl">${esc(exercise.target)}</span></div><div class="production-prompt">${esc(exercise.prompt)}</div><div class="mini muted">Build the complete Dutch sentence. The target word is given; the sentence can vary between encounters so proof reflects use in more than one context.</div><div class="production-answer">${answer?esc(answer):'Your Dutch sentence will appear here'}</div><div class="production-tiles">${remaining.map(x=>`<button class="secondary" data-context-tile="${x.i}">${esc(x.tile)}</button>`).join('')}</div><button id="clear-contextual" class="text-link" ${selected.length?'':'disabled'}>Clear</button><button id="check-contextual" class="primary" ${selected.length===exercise.tiles.length?'':'disabled'}>Check sentence</button><button id="cancel-contextual" class="text-link">Not today</button></article></section>`;document.querySelectorAll('[data-context-tile]').forEach(b=>b.onclick=()=>{selected.push(Number(b.dataset.contextTile));render();});document.getElementById('clear-contextual').onclick=()=>{selected=[];render();};document.getElementById('check-contextual').onclick=()=>finish(s,today,record,exercise,answer);document.getElementById('cancel-contextual').onclick=()=>tab?.click();};render();}

function finish(s,today,record,exercise,answer){const attempt=recordProductionAttempt(s,exercise,answer,{today});saveState(s);content.innerHTML=`<section class="flashcard-session"><article class="card production-card"><div class="production-result ${attempt.correct?'correct':'wrong'}"><div class="production-result-title">${attempt.correct?'Correct sentence':'Not quite'}</div>${attempt.correct?'':`<div class="production-result-row"><span>Your sentence</span><strong lang="nl">${esc(answer||'—')}</strong></div>`}<div class="production-result-row"><span>Model sentence</span><strong lang="nl">${esc(exercise.answer)}</strong></div><div class="production-result-row"><span>English</span><strong>${esc(exercise.prompt)}</strong></div></div><p class="muted small">${attempt.correct?'This counts as contextual production evidence. Once a word is proven, it will be left alone until a later maintenance check is due.':'This word stays in the learning system and can step back to easier production if repeated contextual misses raise its weakness.'}</p><button id="finish-contextual" class="primary">Back to Flashcards</button></article></section>`;document.getElementById('finish-contextual').onclick=()=>tab?.click();}

function refresh(){if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;if(document.querySelector('.production-practice-callout'))inject().catch(()=>{});});}
new MutationObserver(refresh).observe(content,{childList:true,subtree:true});
tab?.addEventListener('click',()=>setTimeout(refresh,0));
refresh();
