import {flashcardSummary,remainingNewCards,buildFlashcardQueue,applyFlashcardRating,productionReadiness,PRODUCTION_STAGE} from '../engine/flashcards.js';
import {STORAGE_KEY} from '../engine/persistence.js';

const tab=document.getElementById('flashcards-preview-tab');
const contentEl=document.getElementById('content');
const message=document.getElementById('system-message');
let loaded=null,session=null;

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dayKey=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const addDays=(date,n)=>{const d=new Date(date);d.setDate(d.getDate()+n);return d;};
const percent=value=>value===null||value===undefined?'—':`${Math.round(value*100)}%`;

function settings(){
  const number=(key,fallback)=>{const n=parseInt(localStorage.getItem(key)??'',10);return Number.isFinite(n)?n:fallback;};
  return {maxNew:number('dfc_max_new',5),retentionThreshold:number('dutch_flashcards_ret_threshold',0),reviewTarget:number('dutch_flashcards_review_target',60)};
}
function learnerState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')||{};}catch{return {};}}
function reviewLoadAllowance(rawLimit,dueReviews,target){if(!target||target<=0)return rawLimit;const ratio=Math.max(0,Number(dueReviews||0))/target;if(ratio>=1)return 0;if(ratio>=.9)return Math.min(rawLimit,Math.max(1,Math.floor(rawLimit*.2)));if(ratio>=.7)return Math.min(rawLimit,Math.max(1,Math.ceil(rawLimit*.5)));return rawLimit;}
function adjustedMaxNew(history,dateToCheck,dueReviews,cfg){const raw=Math.max(0,cfg.maxNew);if(cfg.retentionThreshold>0){const rs=history.filter(r=>r.timestamp&&String(r.timestamp).slice(0,10)===dateToCheck);if(rs.length){const passed=rs.filter(r=>String(r.rating).toLowerCase()!=='again').length;if((passed/rs.length)*100<cfg.retentionThreshold)return 0;}}return Math.min(raw,reviewLoadAllowance(raw,dueReviews,cfg.reviewTarget));}
async function fetchAll(base,key,table){const rows=[],pageSize=1000;for(let from=0;;from+=pageSize){const response=await fetch(`${base}/rest/v1/${table}?select=*`,{headers:{apikey:key,Authorization:`Bearer ${key}`,Range:`${from}-${from+pageSize-1}`,'Range-Unit':'items'}});if(!response.ok)throw new Error(`Could not read ${table} (${response.status}).`);const page=await response.json();rows.push(...page);if(page.length<pageSize)break;}return rows;}
async function loadFlashcards(){const config=await import('https://dabutchart-sudo.github.io/flashcards/constants.js');const [cards,history]=await Promise.all([fetchAll(config.SUPABASE_URL,config.SUPABASE_ANON_KEY,'cards'),fetchAll(config.SUPABASE_URL,config.SUPABASE_ANON_KEY,'reviewhistory')]);return {cards,history,supabaseUrl:config.SUPABASE_URL,key:config.SUPABASE_ANON_KEY};}
function rangeHistory(history,days=30){const cutoff=addDays(new Date(),-(days-1));cutoff.setHours(0,0,0,0);return history.filter(h=>h.timestamp&&new Date(h.timestamp)>=cutoff);}
function troubleWords(cards,history){const byCard=new Map();for(const h of history.filter(x=>x.review_type!=='new')){const id=String(h.cardid??h.card_id??'');if(!id)continue;const s=byCard.get(id)||{again:0,total:0};s.total++;if(String(h.rating).toLowerCase()==='again')s.again++;byCard.set(id,s);}return [...byCard.entries()].map(([id,s])=>{const card=cards.find(c=>String(c.id)===id);if(!card||card.suspended||!s.again)return null;return {card,again:s.again,retention:Math.round(((s.total-s.again)/s.total)*100)};}).filter(Boolean).sort((a,b)=>b.again-a.again||a.retention-b.retention).slice(0,5);}
function counts(data){const {cards,history,supabaseUrl}=data,today=dayKey(),yesterday=dayKey(addDays(new Date(),-1)),cfg=settings();const dueReview=cards.filter(c=>!c.suspended&&c.type!=='new'&&c.due_date&&String(c.due_date).slice(0,10)<=today).length;const introducedToday=cards.filter(c=>!c.suspended&&c.first_seen&&String(c.first_seen).slice(0,10)===today).length;const complete=localStorage.getItem(`dutch_flashcards_completed_v1:${supabaseUrl}:${today}`)==='complete';const maxNew=adjustedMaxNew(history,yesterday,dueReview,cfg);const dueNew=remainingNewCards({configuredMax:cfg.maxNew,loadCap:maxNew,introducedToday,studyDayComplete:complete});return {today,cfg,dueReview,dueNew,complete};}

function render(data){session=null;const {cards,history}=data,{today,cfg,dueReview,dueNew,complete}=counts(data);const last30=rangeHistory(history,30),summary=flashcardSummary(cards,last30),todayReviews=history.filter(h=>h.timestamp&&dayKey(new Date(h.timestamp))===today).length,trouble=troubleWords(cards,last30),queueTotal=dueReview+dueNew;
const readiness=productionReadiness(cards,learnerState()),r=readiness.counts,withLearningEvidence=readiness.records.filter(x=>x.evidence.attempts>0).length,productionPool=r[PRODUCTION_STAGE.SUPPORTED]+r[PRODUCTION_STAGE.GUIDED]+r[PRODUCTION_STAGE.INDEPENDENT]+r[PRODUCTION_STAGE.CONTEXTUAL];
contentEl.innerHTML=`<section class="stack flashcards-preview"><article class="card evidence-card flashcard-hero"><div class="row"><div><div class="eyebrow">Flashcards · migration test</div><h2>${complete?'Flashcards complete for today':`${queueTotal} cards ready`}</h2></div><span class="status">Live data</span></div><p class="muted">The dashboard is read-only. Starting the review session below is an explicit opt-in and ratings will update the same Supabase records used by the standalone app.</p><div class="flashcard-due-grid"><div class="metric"><span class="eyebrow">Reviews due</span><span class="n">${dueReview}</span></div><div class="metric"><span class="eyebrow">New available</span><span class="n">${dueNew}</span></div><div class="metric"><span class="eyebrow">Done today</span><span class="n">${todayReviews}</span></div><div class="metric"><span class="eyebrow">Daily new ceiling</span><span class="n">${cfg.maxNew}</span></div></div><button id="start-flashcard-review" class="primary" ${complete||!queueTotal?'disabled':''}>${complete?'Done for today':queueTotal?'Start review session':'Nothing due'}</button></article>
<article class="card evidence-card"><div class="row"><div><div class="eyebrow">Shared vocabulary evidence</div><h2>English → Dutch readiness</h2></div><span class="status">${productionPool} beyond recognition</span></div><p class="muted">Flashcard maturity now combines with Sentence Trainer evidence to decide how much production support each word should receive. This does not change its SRS interval or your daily Flashcard batch.</p><div class="production-stage-grid"><div class="metric"><span class="eyebrow">Recognise</span><span class="n">${r[PRODUCTION_STAGE.RECOGNITION]}</span><span class="mini">Dutch → English only</span></div><div class="metric"><span class="eyebrow">Supported</span><span class="n">${r[PRODUCTION_STAGE.SUPPORTED]}</span><span class="mini">Choices / strong hints</span></div><div class="metric"><span class="eyebrow">Guided</span><span class="n">${r[PRODUCTION_STAGE.GUIDED]}</span><span class="mini">Tiles / light hints</span></div><div class="metric"><span class="eyebrow">Independent</span><span class="n">${r[PRODUCTION_STAGE.INDEPENDENT]}</span><span class="mini">Type Dutch</span></div><div class="metric"><span class="eyebrow">Contextual</span><span class="n">${r[PRODUCTION_STAGE.CONTEXTUAL]}</span><span class="mini">Use it in a sentence</span></div></div><p class="small muted">${withLearningEvidence} flashcards currently have direct Sentence Trainer attempt evidence. Other cards progress conservatively from their existing SRS maturity until learning evidence is available.</p></article>
<article class="card evidence-card"><div class="row"><div><div class="eyebrow">Last 30 days</div><h2>Flashcard retention</h2></div><div class="flashcard-retention">${percent(summary.retention.rate)}</div></div><p class="muted">${summary.retention.correct} correct from ${summary.retention.total} review attempts. New-card introductions are excluded.</p><div class="flashcard-due-grid"><div class="metric"><span class="eyebrow">Mastered</span><span class="n">${summary.mastered}</span></div><div class="metric"><span class="eyebrow">Active cards</span><span class="n">${summary.active}</span></div><div class="metric"><span class="eyebrow">Suspended</span><span class="n">${summary.suspended}</span></div><div class="metric"><span class="eyebrow">Total cards</span><span class="n">${summary.total}</span></div></div></article><article class="card evidence-card"><div class="eyebrow">Last 30 days</div><h2>Trouble words</h2>${trouble.length?`<div class="recent-mistakes">${trouble.map(x=>`<div class="mistake-row"><div class="row"><strong lang="nl">${esc(x.card.dutch)}</strong><span class="pill">${x.again} Again</span></div><div class="mini">${esc(x.card.english)} · ${x.retention}% retained</div></div>`).join('')}</div>`:'<p class="muted">No troublesome review cards in this period.</p>'}</article></section>`;
document.getElementById('start-flashcard-review')?.addEventListener('click',startSession);}

function startSession(){const c=counts(loaded);if(c.complete||(!c.dueReview&&!c.dueNew))return;if(!confirm(`This development review session writes ratings to your live Flashcards database.\n\nIt will use the same SRS rules as the existing app. Start today's ${c.dueReview+c.dueNew}-card session?`))return;session={day:c.today,queue:buildFlashcardQueue(loaded.cards,{today:c.today,newLimit:c.dueNew}),total:c.dueReview+c.dueNew,flipped:false,busy:false,completed:0};renderCard();}
function current(){return session?.queue?.[0]||null;}
function speakDutch(){const c=current();if(!c)return;const u=new SpeechSynthesisUtterance(String(c.dutch||'').replace(/\s*\(.*?\)/g,'').trim());u.lang='nl-NL';speechSynthesis.cancel();speechSynthesis.speak(u);}
function renderCard(){const c=current();if(!c){localStorage.setItem(`dutch_flashcards_completed_v1:${loaded.supabaseUrl}:${session.day}`,'complete');contentEl.innerHTML=`<section class="flashcards-preview"><article class="card evidence-card complete"><div class="bigcheck">✓</div><h2>Flashcards complete</h2><p class="muted">${session.completed} ratings saved. No more new cards will be offered today.</p><button id="back-dashboard" class="primary">Back to Flashcards</button></article></section>`;document.getElementById('back-dashboard').onclick=async()=>{loaded=await loadFlashcards();render(loaded)};return;}
const done=session.total-session.queue.length,progress=session.total?Math.max(0,Math.min(100,(done/session.total)*100)):0,part=c.partofword?` <span class="muted small">(${esc(c.partofword)})</span>`:'';
contentEl.innerHTML=`<section class="flashcard-session"><div class="session-head"><strong>${session.queue.length} remaining</strong><span class="pill">${c.type==='new'?'New':'Review'}</span></div><div class="progress-track"><div class="progress-fill" style="width:${progress}%"></div></div><article id="review-card" class="card flashcard-review-card" role="button" tabindex="0" aria-label="${session.flipped?'Answer shown':'Reveal answer'}">${session.flipped?`<div class="eyebrow">English</div><div class="flashcard-word">${esc(c.english)}</div>${c.english_sentence?`<div class="flashcard-sentence">${esc(c.english_sentence)}</div>`:''}`:`<div class="eyebrow">Dutch</div><div class="flashcard-word" lang="nl">${esc(c.dutch)}${part}</div>${c.dutch_sentence?`<div class="flashcard-sentence" lang="nl">${esc(c.dutch_sentence)}</div>`:''}<button id="speak-card" class="secondary flashcard-listen">Listen</button>`}</article>${session.flipped?`<div class="flashcard-rating-grid"><button data-rating="again" class="rating again">Again</button><button data-rating="hard" class="rating hard">Hard</button><button data-rating="good" class="rating good">Good</button><button data-rating="easy" class="rating easy">Easy</button></div>`:`<button id="show-answer" class="primary">Show answer</button>`}<button id="leave-review" class="text-link">Pause — saved ratings are kept</button></section>`;
const flip=()=>{if(session.busy||session.flipped)return;session.flipped=true;renderCard();};document.getElementById('show-answer')?.addEventListener('click',flip);document.getElementById('review-card')?.addEventListener('click',e=>{if(e.target.id!=='speak-card')flip()});document.getElementById('review-card')?.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!session.flipped){e.preventDefault();flip();}});document.getElementById('speak-card')?.addEventListener('click',e=>{e.stopPropagation();speakDutch()});document.querySelectorAll('[data-rating]').forEach(b=>b.addEventListener('click',()=>saveRating(b.dataset.rating)));document.getElementById('leave-review').onclick=()=>render(loaded);}

async function request(url,options){const response=await fetch(url,options);if(!response.ok)throw new Error(`Save failed (${response.status}). Stop this session and use the standalone app.`);return response;}
async function saveRating(rating){if(session.busy||!session.flipped)return;session.busy=true;document.querySelectorAll('[data-rating]').forEach(b=>b.disabled=true);const original=current(),result=applyFlashcardRating(original,rating,{today:session.day,nowIso:new Date().toISOString()}),base=loaded.supabaseUrl,key=loaded.key,headers={apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'};
try{await request(`${base}/rest/v1/cards?id=eq.${encodeURIComponent(original.id)}`,{method:'PATCH',headers:{...headers,Prefer:'return=minimal'},body:JSON.stringify({type:result.card.type,interval:result.card.interval,ease:result.card.ease,reps:result.card.reps,lapses:result.card.lapses,first_seen:result.card.first_seen,last_reviewed:result.card.last_reviewed,due_date:result.card.due_date})});await request(`${base}/rest/v1/reviewhistory`,{method:'POST',headers:{...headers,Prefer:'return=minimal'},body:JSON.stringify(result.history)});
Object.assign(original,result.card);const dbCard=loaded.cards.find(x=>String(x.id)===String(original.id));if(dbCard)Object.assign(dbCard,result.card);loaded.history.push(result.history);session.queue.shift();session.completed++;if(result.requeue)session.queue.splice(Math.min(3,session.queue.length),0,original);if(result.leech&&confirm(`This card has now lapsed ${result.card.lapses} times. Suspend it?`)){await request(`${base}/rest/v1/cards?id=eq.${encodeURIComponent(original.id)}`,{method:'PATCH',headers:{...headers,Prefer:'return=minimal'},body:JSON.stringify({suspended:true})});original.suspended=true;if(dbCard)dbCard.suspended=true;session.queue=session.queue.filter(x=>String(x.id)!==String(original.id));}session.flipped=false;renderCard();}catch(error){message.innerHTML=`<div class="error-message">${esc(error.message)}</div>`;session.busy=false;document.querySelectorAll('[data-rating]').forEach(b=>b.disabled=false);}}

async function openPreview(){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b===tab));message.innerHTML='';contentEl.innerHTML='<article class="card evidence-card"><h2>Reading your Flashcards data…</h2></article>';try{loaded=await loadFlashcards();render(loaded);}catch(error){contentEl.innerHTML=`<article class="card evidence-card"><h2>Flashcards could not load</h2><p class="muted">${esc(error.message)}</p><p class="small muted">The existing Flashcards app is unaffected.</p></article>`;}}
if(tab){tab.addEventListener('click',openPreview);document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>tab.classList.remove('active')));}
