import {STORAGE_KEY} from '../engine/persistence.js';
import {recordProductionAttempt,PRODUCTION_DAILY_LIMIT,productionAttemptsToday} from '../engine/flashcards.js';
import {independentRecallCandidates,independentExercise,INDEPENDENT_DAILY_LIMIT,independentAttemptsToday} from '../engine/independent-recall.js';

const content=document.getElementById('content');
const tab=document.getElementById('flashcards-preview-tab');
let cache=null,scheduled=false,busy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dayKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function state(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')||{};}catch{return{};}}
function saveState(s){localStorage.setItem(STORAGE_KEY,JSON.stringify(s));}
async function fetchCards(){if(cache)return cache;const c=await import('https://dabutchart-sudo.github.io/flashcards/constants.js'),rows=[],size=1000;for(let from=0;;from+=size){const res=await fetch(`${c.SUPABASE_URL}/rest/v1/cards?select=*`,{headers:{apikey:c.SUPABASE_ANON_KEY,Authorization:`Bearer ${c.SUPABASE_ANON_KEY}`,Range:`${from}-${from+size-1}`,'Range-Unit':'items'}});if(!res.ok)throw new Error(`Could not read cards (${res.status}).`);const page=await res.json();rows.push(...page);if(page.length<size)break;}cache=rows;return rows;}

async function status(){const s=state(),today=dayKey(),overallLeft=Math.max(0,PRODUCTION_DAILY_LIMIT-productionAttemptsToday(s,today)),independentDone=independentAttemptsToday(s,today);if(!overallLeft||independentDone>=INDEPENDENT_DAILY_LIMIT)return {available:0,done:independentDone,overallLeft};try{return {available:(await independentRecallCandidates(await fetchCards(),s,{today})).length,done:independentDone,overallLeft};}catch{return {available:0,done:independentDone,overallLeft};}}

async function inject(){const callout=document.querySelector('.production-practice-callout');if(!callout||document.getElementById('independent-recall-pilot'))return;const host=document.createElement('div');host.id='independent-recall-pilot';host.className='independent-recall-pilot';host.innerHTML='<div><strong>Independent recall pilot</strong><div class="mini">Checking readiness…</div></div><button class="secondary" disabled>Loading…</button>';callout.insertAdjacentElement('afterend',host);const info=await status();if(!host.isConnected)return;const text=host.querySelector('.mini'),button=host.querySelector('button');if(info.done){text.textContent='Today’s independent question is complete. One is the daily maximum for now.';button.textContent='Done for today';button.disabled=true;return;}if(!info.overallLeft){text.textContent='Your five active-recall questions are already complete today.';button.textContent='Done for today';button.disabled=true;return;}if(!info.available){text.textContent='No words are ready for unsupported English → Dutch recall yet.';button.textContent='Not ready yet';button.disabled=true;return;}text.textContent='One word only. No hints or tiles — type the Dutch answer from memory. It counts within today’s five active-recall questions.';button.textContent='Try 1 independent word';button.disabled=false;button.onclick=start;}

async function start(){if(busy)return;busy=true;try{const s=state(),today=dayKey(),cards=await fetchCards(),candidate=(await independentRecallCandidates(cards,s,{today}))[0];if(!candidate){tab?.click();return;}renderQuestion(s,today,candidate,independentExercise(candidate));}catch(e){alert(e.message);}finally{busy=false;}}

function renderQuestion(s,today,record,exercise){content.innerHTML=`<section class="flashcard-session"><article class="card production-card independent-production-card"><div class="eyebrow">Independent · English → Dutch</div><div class="production-prompt">${esc(exercise.prompt)}</div><div class="mini muted">Type the Dutch answer from memory. There is no spelling hint on this one.</div><div class="production-spelling"><input id="independent-recall-input" class="production-input" type="text" lang="nl" autocomplete="off" autocapitalize="none" spellcheck="false" placeholder="Type the Dutch word or phrase"><button id="check-independent-recall" class="primary" disabled>Check answer</button></div><button id="cancel-independent-recall" class="text-link">Not today</button></article></section>`;const input=document.getElementById('independent-recall-input'),check=document.getElementById('check-independent-recall');input.addEventListener('input',()=>check.disabled=!input.value.trim());input.addEventListener('keydown',e=>{if(e.key==='Enter'&&input.value.trim())finish(s,today,exercise,input.value.trim())});check.onclick=()=>finish(s,today,exercise,input.value.trim());document.getElementById('cancel-independent-recall').onclick=()=>tab?.click();input.focus();}

function finish(s,today,exercise,answer){const attempt=recordProductionAttempt(s,exercise,answer,{today});saveState(s);const correct=attempt.correct;content.innerHTML=`<section class="flashcard-session"><article class="card production-card"><div class="production-result ${correct?'correct':'wrong'}"><div class="production-result-title">${correct?'Correct':'Not quite'}</div>${correct?`<div class="production-result-row"><span>Answer</span><strong lang="nl">${esc(exercise.answer)}</strong></div>`:`<div class="production-result-row"><span>Your answer</span><strong lang="nl">${esc(answer||'—')}</strong></div><div class="production-result-row"><span>Correct answer</span><strong lang="nl">${esc(exercise.answer)}</strong></div>`}</div><p class="muted small">That was today’s single independent-recall question. ${correct?'A correct answer counts as independent production evidence.':'A miss increases this word’s weakness evidence, so the app can support it more before asking independently again.'}</p><button id="finish-independent-recall" class="primary">Back to Flashcards</button></article></section>`;document.getElementById('finish-independent-recall').onclick=()=>tab?.click();}

function refresh(){if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;if(document.querySelector('.production-practice-callout'))inject().catch(()=>{});});}
new MutationObserver(refresh).observe(content,{childList:true,subtree:true});
tab?.addEventListener('click',()=>setTimeout(refresh,0));
refresh();
