import {REPORT_RANGES,dailyActivity,dailyRetention,ratingBreakdown,upcomingReviews,cardStatus,reportSummary} from '../engine/reporting.js';
const tab=document.getElementById('report-tab'),host=document.getElementById('content');let loaded=null,range='30';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function fetchAll(base,key,table){const rows=[],size=1000;for(let from=0;;from+=size){const r=await fetch(`${base}/rest/v1/${table}?select=*`,{headers:{apikey:key,Authorization:`Bearer ${key}`,Range:`${from}-${from+size-1}`,'Range-Unit':'items'}});if(!r.ok)throw Error(`Could not read ${table} (${r.status}).`);const page=await r.json();rows.push(...page);if(page.length<size)break;}return rows;}
async function load(){const c=await import('https://dabutchart-sudo.github.io/flashcards/constants.js'),[cards,history]=await Promise.all([fetchAll(c.SUPABASE_URL,c.SUPABASE_ANON_KEY,'cards'),fetchAll(c.SUPABASE_URL,c.SUPABASE_ANON_KEY,'reviewhistory')]);return{cards,history};}
const shortDate=s=>new Date(s+'T12:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short'});
function majorTick(index,length){const step=length<=10?1:length<=18?2:Math.ceil(length/7);return index===0||index===length-1||index%step===0;}
function bars(rows,keys,{labels=false,barClass=null}={}){const max=Math.max(1,...rows.map(r=>keys.reduce((n,k)=>n+(r[k]||0),0))),shown=rows.length>35?rows.filter((_,i)=>i%Math.ceil(rows.length/35)===0||i===rows.length-1):rows;return `<div class="report-bars">${shown.map((r,index)=>{const total=keys.reduce((n,k)=>n+(r[k]||0),0),major=majorTick(index,shown.length);return `<div class="report-bar-col" title="${esc(shortDate(r.date))}: ${keys.map(k=>`${k} ${r[k]||0}`).join(', ')}"><div class="report-bar-stack">${keys.map(k=>{const value=r[k]||0,height=Math.max(value?4:0,value/max*150),cls=barClass||k;return `<span class="report-bar ${cls}" style="height:${height}px">${labels&&keys.length===1?`<b class="report-bar-value">${total}</b>`:''}</span>`}).join('')}</div><span class="report-date-label ${major?'axis-major':''}">${esc(shortDate(r.date))}</span></div>`}).join('')}</div>`;}
function retentionChart(rows){if(!rows.length)return'<p class="report-empty">No review history in this period.</p>';const shown=rows.length>35?rows.filter((_,i)=>i%Math.ceil(rows.length/35)===0||i===rows.length-1):rows;return `<div class="retention-bars">${shown.map((r,index)=>`<div class="retention-col" title="${esc(shortDate(r.date))}: ${Math.round(r.rate*100)}%"><div class="retention-track"><span style="height:${Math.max(2,r.rate*100)}%"></span></div><small class="${majorTick(index,shown.length)?'axis-major':''}">${Math.round(r.rate*100)}%</small></div>`).join('')}</div>`;}
function render(){const {cards,history}=loaded,s=reportSummary(cards,history,range),activity=dailyActivity(history,range),retention=dailyRetention(history,range),ratings=ratingBreakdown(history,range),future=upcomingReviews(cards,14),status=cardStatus(cards),rangeLabel=REPORT_RANGES.find(x=>x.value===range)?.label||range;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===tab));host.innerHTML=`<section class="stack report-view"><button type="button" id="back-to-flashcards" class="text-link">← Flashcards</button><div class="report-head"><div><div class="eyebrow">FLASHCARD REPORTING</div><h2>Study progress</h2></div><div class="report-ranges">${REPORT_RANGES.map(x=>`<button class="${x.value===range?'active':''}" data-range="${x.value}">${x.label}</button>`).join('')}</div></div><div class="report-summary">${[['Studied',s.total],['New',s.newCards],['Reviewed',s.reviewed],['Recall',s.retention==null?'—':Math.round(s.retention*100)+'%'],['Mature',s.mature]].map(([l,v])=>`<article class="card"><span>${l}</span><strong>${v}</strong></article>`).join('')}</div><article class="card report-card"><h3>Daily Study Load</h3><p>New cards and review attempts each day · ${rangeLabel}</p>${activity.length?bars(activity,['new','reviewed']):'<p class="report-empty">No study activity in this period.</p>'}<div class="report-legend"><span><i class="new"></i>New</span><span><i class="reviewed"></i>Reviewed</span></div></article><article class="card report-card"><h3>Recall Rate</h3><p>Successful review attempts each study day. New-card introductions are excluded.</p>${retentionChart(retention)}</article><article class="card report-card"><h3>Review Ratings</h3><p>How review cards felt over ${rangeLabel.toLowerCase()}.</p><div class="rating-grid">${['again','hard','good','easy'].map(k=>`<div class="rating-stat ${k}"><strong>${ratings.total?Math.round(ratings.percentages[k]*100):0}%</strong><span>${k[0].toUpperCase()+k.slice(1)}</span><small>${ratings.counts[k]} reviews</small></div>`).join('')}</div></article><article class="card report-card"><h3>Current Card Progress</h3><p>A truthful snapshot of where the card collection is now; historical card states were not recorded, so this is not presented as a trend.</p><div class="status-grid">${[['New',status.new],['Learning',status.learning],['Mature',status.mature],['Suspended',status.suspended]].map(([l,v])=>`<div><strong>${v}</strong><span>${l}</span></div>`).join('')}</div></article><article class="card report-card"><h3>Upcoming Review Load</h3><p>Reviews currently scheduled over the next 14 days. Overdue cards are included in today.</p>${bars(future,['count'],{labels:true,barClass:'upcoming'})}</article></section>`;host.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{range=b.dataset.range;render();});document.getElementById('back-to-flashcards')?.addEventListener('click',()=>document.getElementById('flashcards-preview-tab')?.click());}
async function open(){host.innerHTML='<article class="card evidence-card"><h2>Loading reports…</h2></article>';try{loaded=await load();render();}catch(e){host.innerHTML=`<article class="card evidence-card"><h2>Reports unavailable</h2><p>${esc(e.message)}</p></article>`;}}
tab?.addEventListener('click',open);
