import {searchableCards,wordBrowserSummary,WORD_BROWSER_LIMIT} from '../engine/word-browser.js';
import {clearSentenceGenerationReturn,generateSentenceBanks,sentenceGenerationReturnTarget,sentenceGenerationUser,signInForSentenceGeneration} from './sentence-bank-client.js';

const tab=document.getElementById('words-tab'),content=document.getElementById('content');
let cache=null,busy=false,lastQuery='',filter='all',sort='dutch';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function config(){return import('https://dabutchart-sudo.github.io/flashcards/constants.js');}
async function fetchCards(force=false){if(cache&&!force)return cache;const c=await config(),rows=[],size=1000;for(let from=0;;from+=size){const res=await fetch(`${c.SUPABASE_URL}/rest/v1/cards?select=*`,{headers:{apikey:c.SUPABASE_ANON_KEY,Authorization:`Bearer ${c.SUPABASE_ANON_KEY}`,Range:`${from}-${from+size-1}`,'Range-Unit':'items'}});if(!res.ok)throw Error(`Could not read words (${res.status}).`);const page=await res.json();rows.push(...page);if(page.length<size)break;}cache=rows;return rows;}
async function patchCard(id,body){const c=await config(),res=await fetch(`${c.SUPABASE_URL}/rest/v1/cards?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{apikey:c.SUPABASE_ANON_KEY,Authorization:`Bearer ${c.SUPABASE_ANON_KEY}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(body)});if(!res.ok)throw Error(`Could not save card (${res.status}).`);}
async function deleteCard(id){const c=await config(),res=await fetch(`${c.SUPABASE_URL}/rest/v1/cards?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:{apikey:c.SUPABASE_ANON_KEY,Authorization:`Bearer ${c.SUPABASE_ANON_KEY}`,Prefer:'return=minimal'}});if(!res.ok)throw Error(`Could not delete card (${res.status}).`);}
function activateTab(){document.querySelectorAll('.tab').forEach(node=>node.classList.toggle('active',node===tab));}
function row(card){const sentence=card.dutch_sentence||card.english_sentence||'';return `<article class="word-browser-row">${card.image_url?`<img src="${esc(card.image_url)}" alt="" loading="lazy">`:''}<div class="word-browser-copy"><div class="word-browser-title"><strong lang="nl">${esc(card.dutch)}</strong>${card.partofword?`<span class="pill">${esc(card.partofword)}</span>`:''}${card.suspended?'<span class="pill">Frozen</span>':''}</div><div class="word-browser-english">${esc(card.english)}</div>${sentence?`<div class="word-browser-sentence" lang="nl">${esc(sentence)}</div>`:'<div class="word-browser-sentence muted">No example sentence yet.</div>'}<div class="word-browser-actions"><button class="text-link" data-edit-card="${esc(card.id)}">Edit</button><button class="text-link" data-freeze-card="${esc(card.id)}">${card.suspended?'Unfreeze':'Freeze'}</button><button class="text-link" data-sentence-card="${esc(card.id)}">${sentence?'Replace sentence':'Add sentence'}</button></div></div></article>`;}
function currentResults(cards){return searchableCards(cards,lastQuery,{filter,sort,limit:WORD_BROWSER_LIMIT});}
function bindRows(cards){document.querySelectorAll('[data-sentence-card]').forEach(b=>b.onclick=()=>openSentenceMaintenance(b.dataset.sentenceCard));document.querySelectorAll('[data-edit-card]').forEach(b=>b.onclick=()=>openEditor(b.dataset.editCard));document.querySelectorAll('[data-freeze-card]').forEach(b=>b.onclick=()=>toggleFreeze(b.dataset.freezeCard));}
function renderList(cards){const results=currentResults(cards),host=document.getElementById('word-browser-results'),count=document.getElementById('word-browser-count');if(!host||!count)return;count.textContent=`${results.length}${results.length===WORD_BROWSER_LIMIT?'+':''} word${results.length===1?'':'s'}`;host.innerHTML=results.length?results.map(row).join(''):'<div class="empty">No matching words.</div>';bindRows(cards);}
async function open(){if(busy)return;busy=true;activateTab();content.innerHTML='<article class="card evidence-card"><h2>Opening your words…</h2></article>';try{const cards=await fetchCards(),s=wordBrowserSummary(cards);content.innerHTML=`<section class="word-browser"><article class="card evidence-card word-browser-head"><div class="eyebrow">WORDS</div><h2>Vocabulary browser</h2><p class="muted">Search and maintain the live flashcard collection without changing review scheduling unless you explicitly freeze a card.</p><div class="word-browser-metrics"><div class="metric"><span class="eyebrow">Active</span><span class="n">${s.active}</span></div><div class="metric"><span class="eyebrow">Sentences</span><span class="n">${s.withSentence}</span></div><div class="metric"><span class="eyebrow">Images</span><span class="n">${s.withImage}</span></div></div><input id="word-browser-search" class="word-browser-search" type="search" autocomplete="off" placeholder="Search Dutch, English, type or sentence" value="${esc(lastQuery)}"><div class="word-browser-controls"><div class="word-browser-filters">${[['all','All'],['due','Due'],['new','New'],['frozen','Frozen']].map(([v,l])=>`<button data-filter="${v}" class="${filter===v?'active':''}">${l}</button>`).join('')}</div><select id="word-browser-sort"><option value="dutch" ${sort==='dutch'?'selected':''}>A–Z Dutch</option><option value="english" ${sort==='english'?'selected':''}>A–Z English</option><option value="recent" ${sort==='recent'?'selected':''}>Recently reviewed</option></select></div><div id="word-browser-count" class="mini muted"></div></article><div id="word-browser-results" class="word-browser-results"></div></section>`;const input=document.getElementById('word-browser-search');input.oninput=()=>{lastQuery=input.value;renderList(cards)};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;open()});document.getElementById('word-browser-sort').onchange=e=>{sort=e.target.value;renderList(cards)};renderList(cards);}catch(e){content.innerHTML=`<article class="card evidence-card"><h2>Could not open Words</h2><p class="error-message">${esc(e.message)}</p></article>`;}finally{busy=false;}}
async function toggleFreeze(id){const cards=await fetchCards(),card=cards.find(c=>String(c.id)===String(id));if(!card)return;try{await patchCard(card.id,{suspended:!card.suspended});card.suspended=!card.suspended;await open();}catch(e){alert(e.message);}}
async function openEditor(id){const cards=await fetchCards(),card=cards.find(c=>String(c.id)===String(id));if(!card)return;content.innerHTML=`<section class="word-browser"><article class="card evidence-card word-editor"><div class="eyebrow">EDIT FLASHCARD</div><h2>${esc(card.dutch)}</h2><label>Dutch<input id="we-dutch" value="${esc(card.dutch)}"></label><label>English<input id="we-english" value="${esc(card.english)}"></label><label>Word type<input id="we-part" value="${esc(card.partofword||'')}"></label><label>Dutch sentence<textarea id="we-nl-sentence">${esc(card.dutch_sentence||'')}</textarea></label><label>English sentence<textarea id="we-en-sentence">${esc(card.english_sentence||'')}</textarea></label><label>Image URL<input id="we-image" value="${esc(card.image_url||'')}" placeholder="https://…"></label>${card.image_url?`<img class="word-editor-preview" src="${esc(card.image_url)}" alt="Current image">`:''}<div id="word-editor-status" class="small muted"></div><div class="word-editor-actions"><button id="we-back" class="secondary">Cancel</button><button id="we-save" class="primary">Save changes</button></div><button id="we-delete" class="text-link danger">Delete card</button></article></section>`;document.getElementById('we-back').onclick=open;document.getElementById('we-save').onclick=async()=>{const status=document.getElementById('word-editor-status');try{status.textContent='Saving…';const body={dutch:document.getElementById('we-dutch').value.trim(),english:document.getElementById('we-english').value.trim(),partofword:document.getElementById('we-part').value.trim()||null,dutch_sentence:document.getElementById('we-nl-sentence').value.trim()||null,english_sentence:document.getElementById('we-en-sentence').value.trim()||null,image_url:document.getElementById('we-image').value.trim()||null};if(!body.dutch||!body.english)throw Error('Dutch and English are required.');await patchCard(card.id,body);Object.assign(card,body);await open();}catch(e){status.textContent=e.message;}};document.getElementById('we-delete').onclick=async()=>{if(!confirm(`Delete “${card.dutch}” permanently? This cannot be undone.`))return;try{await deleteCard(card.id);cache=cards.filter(c=>String(c.id)!==String(card.id));await open();}catch(e){alert(e.message);}};}

async function openSentenceMaintenance(cardId){const cards=await fetchCards(),card=cards.find(item=>String(item.id)===String(cardId));if(!card)return;activateTab();let user=null;try{user=await sentenceGenerationUser();}catch{}content.innerHTML=`<section class="word-browser sentence-maintenance"><article class="card evidence-card"><div class="eyebrow">SENTENCE MAINTENANCE</div><h2><span lang="nl">${esc(card.dutch)}</span> · ${esc(card.english)}</h2><p class="muted">Generate five fresh examples, choose one, and save it. SRS is unchanged.</p>${card.dutch_sentence?`<div class="sentence-maintenance-current"><strong lang="nl">${esc(card.dutch_sentence)}</strong><span>${esc(card.english_sentence||'')}</span></div>`:''}<div class="sentence-maintenance-actions">${user?'<button id="generate-replacement-sentences" class="primary">Generate 5 new sentences</button>':'<button id="signin-replacement-sentences" class="secondary">Sign in with Google to generate</button>'}<button id="cancel-sentence-maintenance" class="text-link">Back to Words</button></div><div id="sentence-maintenance-status" class="small muted"></div><div id="sentence-maintenance-options"></div></article></section>`;document.getElementById('cancel-sentence-maintenance').onclick=open;document.getElementById('signin-replacement-sentences')?.addEventListener('click',async()=>{const s=document.getElementById('sentence-maintenance-status');try{s.textContent='Opening Google sign-in…';sessionStorage.setItem('sentence_maintenance_card',String(card.id));await signInForSentenceGeneration('words');}catch(e){s.textContent=e.message;}});document.getElementById('generate-replacement-sentences')?.addEventListener('click',()=>generateReplacementOptions(card));}
async function generateReplacementOptions(card){const button=document.getElementById('generate-replacement-sentences'),status=document.getElementById('sentence-maintenance-status'),host=document.getElementById('sentence-maintenance-options');button.disabled=true;button.textContent='Generating…';status.textContent='Creating five fresh sentence pairs…';host.innerHTML='';try{const result=await generateSentenceBanks([card],{force:true}),generated=result.cards[0]?.generatedSentences||[];if(generated.length!==5)throw Error('Expected five generated sentence pairs.');status.textContent='Choose the example you want to use.';host.innerHTML=`<div class="sentence-maintenance-list">${generated.map((pair,index)=>`<button class="sentence-maintenance-option" data-sentence-choice="${index}"><strong lang="nl">${esc(pair.nl)}</strong><span>${esc(pair.en)}</span></button>`).join('')}</div>`;host.querySelectorAll('[data-sentence-choice]').forEach(choice=>choice.onclick=()=>saveReplacementSentence(card,generated[Number(choice.dataset.sentenceChoice)]));}catch(e){status.textContent=e.message;button.disabled=false;button.textContent='Try generation again';}}
async function saveReplacementSentence(card,pair){const status=document.getElementById('sentence-maintenance-status'),host=document.getElementById('sentence-maintenance-options');try{await patchCard(card.id,{dutch_sentence:pair.nl,english_sentence:pair.en});card.dutch_sentence=pair.nl;card.english_sentence=pair.en;status.textContent='Saved. SRS and today’s session were not changed.';host.innerHTML=`<div class="sentence-maintenance-current saved"><strong lang="nl">${esc(pair.nl)}</strong><span>${esc(pair.en)}</span></div><button id="sentence-maintenance-done" class="primary">Back to Words</button>`;document.getElementById('sentence-maintenance-done').onclick=open;}catch(e){status.textContent=e.message;}}
async function restoreSentenceMaintenance(){if(sentenceGenerationReturnTarget()!=='words')return;let user=null;for(let attempt=0;attempt<20&&!user;attempt++){try{user=await sentenceGenerationUser();}catch{}if(!user)await wait(100);}if(!user)return;const cardId=sessionStorage.getItem('sentence_maintenance_card');sessionStorage.removeItem('sentence_maintenance_card');clearSentenceGenerationReturn();if(cardId)await openSentenceMaintenance(cardId);else await open();}
tab?.addEventListener('click',open);setTimeout(()=>restoreSentenceMaintenance().catch(()=>{}),0);
